default:
  tags:
    - whitelabel-staging
    
stages:
  - build

variables:
  DO_REGISTRY: registry.digitalocean.com/bbq
  DO_IMAGE_TAG: ${DO_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}
  DO_IMAGE_TAG_ALTERNATIVE: ${DO_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}
  GITLAB_IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}

build-package:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  variables:
    DOCKER_BUILD_CONTEXT: "."
  script:
    - echo "Building BackstopJS"
    - echo ${DOCKER_AUTH_CONFIG} > /kaniko/.docker/config.json
    - /kaniko/executor --use-new-run --snapshotMode=redo --destination ${DO_IMAGE_TAG} --destination ${DO_IMAGE_TAG_ALTERNATIVE} --context "${DOCKER_BUILD_CONTEXT}"

build-source:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  variables:
    DOCKER_BUILD_CONTEXT: "."
  script:
    - echo "Building source container"
    - echo ${DOCKER_AUTH_CONFIG} > /kaniko/.docker/config.json
    - /kaniko/executor --dockerfile "./modules/Dockerfile" --destination ${DO_IMAGE_TAG}-modules --context "${DOCKER_BUILD_CONTEXT}" --single-snapshot
  only:
    refs:
      - merge_requests
    changes:
      - "**/package.json"
      - "**/yarn.lock"
