include:
  - project: common/gitlab-ci-templates
    file: "/build/common-variables-latest.yaml"
    ref: master
  - project: common/gitlab-ci-templates
    file: "/publish/publish-to-argocd-1.0.1.yaml"
    ref: master

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "develop"'

stages:
  - build-source
  - build
  - publish

variables:
  DO_REGISTRY: registry.digitalocean.com/bbq
  DO_IMAGE_TAG: ${DO_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}
  DO_SOURCE_IMAGE_TAG: ${DO_REGISTRY}/${CI_PROJECT_NAME}:develop
  DO_IMAGE_TAG_ALTERNATIVE: ${DO_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}_${CI_PIPELINE_ID}
  GITLAB_IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}

build-package:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  variables:
    DOCKER_BUILD_CONTEXT: "."
  script:
    - echo "Building BackstopJS"
    - 'echo "{ \"auths\": { \"$DO_REGISTRY\": { \"username\": \"$DO_REGISTRY_TOKEN\", \"password\": \"$DO_REGISTRY_TOKEN\" } }, \"credHelpers\": { \"$DOCKER_REGISTRY\": \"ecr-login\" } }" > "/kaniko/.docker/config.json"'
    - >
      /kaniko/executor \
        --destination ${DO_IMAGE_TAG} \
        --destination ${DO_IMAGE_TAG_ALTERNATIVE} \
        --destination ${IMAGE} \
        --destination ${IMAGE_HASH} \
        --context "${DOCKER_BUILD_CONTEXT}" \
        --single-snapshot
  rules:
    - if: $CI_COMMIT_REF_NAME

build-source:
  stage: build-source
  image: gcr.io/kaniko-project/executor:debug
  variables:
    DOCKER_BUILD_CONTEXT: "."
  script:
    - echo "Building source container"
    - 'echo "{ \"auths\": { \"$DO_REGISTRY\": { \"username\": \"$DO_REGISTRY_TOKEN\", \"password\": \"$DO_REGISTRY_TOKEN\" } }, \"credHelpers\": { \"$DOCKER_REGISTRY\": \"ecr-login\" } }" > "/kaniko/.docker/config.json"'
    - >
      /kaniko/executor \
        --dockerfile "./modules/Dockerfile" \
        --destination "${DO_SOURCE_IMAGE_TAG}-modules" \
        --destination "${IMAGE}-modules" \
        --context "${DOCKER_BUILD_CONTEXT}" \
        --single-snapshot
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - modules/Dockerfile
        - "**/package.json"
        - "**/yarn.lock"

publish to development:
  extends: .publish-to-argocd
  variables:
    PUBLISH_TO_ENV: "development"
    HELM_VALUES_PATH: "./values/development.yaml"
    DESTINATION_NAMESPACE: ${CI_PROJECT_NAME}
  stage: publish
  rules:
    - changes:
        paths:
          - modules/Dockerfile
          - "**/package.json"
          - "**/yarn.lock"
      when: never
    - if: $CI_COMMIT_REF_NAME == "develop"

publish to staging:
  extends: .publish-to-argocd
  variables:
    PUBLISH_TO_ENV: "staging"
    HELM_VALUES_PATH: "./values/staging.yaml"
    DESTINATION_NAMESPACE: ${CI_PROJECT_NAME}
  stage: publish
  rules:
    - changes:
        paths:
          - modules/Dockerfile
          - "**/package.json"
          - "**/yarn.lock"
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
