---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.hostname }}
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-certs
  secretName: {{ printf "%s.tls" .Values.ingress.hostname }}
  dnsNames:
    - {{ .Values.ingress.hostname }}
