apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/application: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Values.componentId }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | indent 4 }}
    {{- end }}
    nginx.org/client-max-body-size: 512m
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: "{{ .Values.ingress.hostname }}.tls"
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
