apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/application: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Values.componentId }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/application: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Values.componentId }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
