componentId: 'toledo'
env_value: production
replicas: 1
port: 3000

resources:
  requests:
    cpu: 400m
    memory: 3000Mi
  limits:
     memory: 3000Mi

image:
  name: 'localhost'
  tag: 'master'

ingress:
  hostname: "localhost"
#  cfIpList: ''
  annotations: []

env:
  alpa_addr: localhost:2004
  thor_addr: localhost:2004
  is_aws: "false"

volume:
  size: 1Gi
  testSize: 20Gi
